### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by eholzbach** [conformal/spectrwm#104]
Fails to build on FreeBSD since commit 42bccafc30073c1428d63b93d5db8b749491c8d4

spectrwm.c:6377:2: error: type name requires a specifier or qualifier
        SIMPLEQ_ENTRY(event)    entry;
        ^
spectrwm.c:6377:16: error: a parameter list without types is only allowed in a function definition
        SIMPLEQ_ENTRY(event)    entry;
                      ^
spectrwm.c:6377:22: error: expected ';' at end of declaration list
        SIMPLEQ_ENTRY(event)    entry;
                            ^
                            ;
spectrwm.c:6380:34: error: expected function body after function declarator
SIMPLEQ_HEAD(event_queue, event) events = SIMPLEQ_HEAD_INITIALIZER(events);
                                 ^
spectrwm.c:6389:12: warning: implicit declaration of function 'SIMPLEQ_FIRST' is invalid in C99 [-Wimplicit-function-declaration]
        if ((ep = SIMPLEQ_FIRST(&events))) {
                  ^
spectrwm.c:6389:27: error: use of undeclared identifier 'events'
        if ((ep = SIMPLEQ_FIRST(&events))) {
                                 ^
spectrwm.c:6391:3: warning: implicit declaration of function 'SIMPLEQ_REMOVE_HEAD' is invalid in C99 [-Wimplicit-function-declaration]
                SIMPLEQ_REMOVE_HEAD(&events, entry);
                ^
spectrwm.c:6391:24: error: use of undeclared identifier 'events'
                SIMPLEQ_REMOVE_HEAD(&events, entry);
                                     ^
spectrwm.c:6408:2: warning: implicit declaration of function 'SIMPLEQ_INSERT_HEAD' is invalid in C99 [-Wimplicit-function-declaration]
        SIMPLEQ_INSERT_HEAD(&events, ep, entry);
        ^
spectrwm.c:6408:23: error: use of undeclared identifier 'events'
        SIMPLEQ_INSERT_HEAD(&events, ep, entry);
                             ^
3 warnings and 7 errors generated.
*** Error code 1

**Comment by LordReg** [comment]
Should be fixed on master, could you give it a try?
